---
title: "Week 3 Lab: Fundamental Chart Types"
author: "Jaslyn Miura"
date: "January 22, 2026"
format: html
---

```{r}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                                    setup                                 ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#..........................load packages.........................
library(tidyverse)
library(scales)

#..........................import data...........................
drought <- readr::read_csv(here::here('week3/data/dm_export_20000101_20260121.csv'))

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                            wrangle drought data                          ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

drought_clean <- drought |>
  
  # Pivot table to be in tidy form
 pivot_longer(cols = None:D4, names_to = "drought_lvl",    values_to = "area_pct") |>
  
  janitor::clean_names() |>
  
  # Rename state abbreviation column
   rename(state_abb = state_abbreviation) |>

  # select cols of interest & update names for clarity (as needed) ----
  select(date = valid_start, state_abb, drought_lvl, area_pct) |> 

  # add year, month & day cols using {lubridate} fxns ----
  # NOTE: this step isn't necessary for our plot, but I'm including as examples of how to extract different date elements from a object of class `Date` using {lubridate} ----
  mutate(year = year(date),
         month = month(date, label = TRUE, abbr = TRUE),
         day = day(date)) |>

  # add drought level conditions names ----
  mutate(drought_lvl_long = factor(drought_lvl,
                            levels = c("D4", "D3", "D2", "D1","D0", "None"),
                            labels = c("(D4) Exceptional", "(D3) Extreme",
                                       "(D2) Severe", "(D1) Moderate", 
                                       "(D0) Abnormally Dry", 
                                       "No Drought"))) |>
  
  # reorder cols ----
  relocate(date, year, month, day, state_abb, drought_lvl, drought_lvl_long, area_pct)
```

```{r}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##       create stacked area plot of CA drought conditions through time     ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

drought_clean |> 
  
  # remove drought_lvl "None" & filter for just CA ----
  filter(drought_lvl != "None",
         state_abb == "CA") |> 
  
  # pipe into ggplot here!
  ggplot(aes(x = date, y = area_pct, group = drought_lvl, fill = drought_lvl_long)) +
  geom_area() + 
  scale_fill_manual(values = c("#853904", "#FF0000", "#FFC100", "#FFE79A", "#FFFF04")) +
  scale_x_date(date_breaks = "2 year", 
               date_labels = "%Y",
               expand = c(0, 0),
               limits = as.Date(c("2000-01-01", "2026-12-31"))) +
  scale_y_continuous(expand = c(0, 0),
                     labels = scales::label_percent(scale = 1),
                     breaks = seq(from = 0, to = 100, by = 10)) +
  labs(x = "",
       y = "",
       fill = "",
       title = "Drought Area in California") +
  theme_minimal() +
  theme(
    axis.title = element_blank(),
    axis.line = element_line(color = "#64A1D8"),
    axis.ticks = element_line(color = "#64A1D8"),
    legend.position = "bottom", 
    # panel.background = element_rect(fill = "white"),
    # panel.grid.major = element_line(color = "grey",
    plot.title = element_text(hjust = 0.5),
    legend.key.width = unit(0.4, "cm"),
    legend.key.height = unit(0.25, "cm"), 
    plot.margin = margin(t = 10, r = 4, b = 10, l = 4))
  
  
  
```

